### ISSUE TITLE
Add links to website

### ISSUE THREAD

**Issue by sahilc0** [futurepaul/abdc#3]
[The dribbblisation of design
](https://www.intercom.com/blog/the-dribbblisation-of-design/)

[Quick font pairings: Google Fonts
](https://www.figma.com/community/file/1113950611695632368)

[Block research summarized by Skyler](https://twitter.com/skyler_fs/status/1531732645213790210)

[Figma Config updates](https://twitter.com/figma/status/1524052372871270400)

[Figma spring animations](https://www.figma.com/blog/how-we-built-spring-animations/)

[React-spring](https://react-spring.dev/#introduction)

[Lil' details 1](https://twitter.com/DanHollick/status/1542067959706828802)

[Lil' details 2](https://twitter.com/brian_lovin/status/1540075092134313984)

[A product design process for the real world](https://www.tedgoas.com/blog/product-design-process/)

[Modal vs Pages framework](https://uxplanet.org/modal-vs-page-a-decision-making-framework-34453e911129)

[Yellows are fricking hard. ](https://uxdesign.cc/the-dark-yellow-problem-in-design-system-color-palettes-a0db1eedc99d)

[There is no fold - LukeW](https://www.lukew.com/ff/entry.asp?1946)

[Why does a design look good? ](https://www.nngroup.com/articles/why-does-design-look-good/)

[What are design tokens and how to name them? ](https://www.gerireid.com/design-token-taxonomy.html)

[Behind the scenes of Figma dark mode and tokens ](https://twitter.com/ryhanhassan/status/1524055454929670145)

[Github dark mode tooling](https://github.blog/2022-06-14-accelerating-github-theme-creation-with-color-tooling/)

[Storybook 7.0 update](https://storybook.js.org/blog/storybook-7-0-design-sneak-peek/)

[Design systems are flawed](https://ux.shopify.com/design-systems-are-flawed-eecb60610efa)

**Comment by sahilc0** [comment]
Feel free to close this issue once added to the website @futurepaul ! Thanks broseph

**Comment by futurepaul** [comment]
merged!
