### ISSUE TITLE
Make meetup.com link more clear

### ISSUE THREAD

**Issue by sahilc0** [futurepaul/abdc#5]
![image](https://user-images.githubusercontent.com/8256062/181590374-41f88273-f7ff-4c4c-9d97-cf6475630312.png)

**Current**
- It's a little hard to tell this is a meetup link, since there's only four characters. Pretty easy to miss at least for me (I've missed it a few times already hahaha)

**Change request proposal**
- Maybe we can increase string length? Something like "Meetup.com: rsvp" or "RSVP on Meetup.com"?

**Comment by futurepaul** [comment]
good call

**Comment by sahilc0** [comment]
Paul did it, absolute chad
