### ISSUE TITLE
September topic ideas

### ISSUE THREAD

**Issue by sahilc0** [futurepaul/abdc#7]

**Comment by sahilc0** [comment]
https://uxdesign.cc/design-principles-why-a-design-works-a572c5d2d92d

**Comment by sahilc0** [comment]
https://twitter.com/buchiux/status/1555270438535692290

**Comment by sahilc0** [comment]
https://jlzych.com/2022/06/06/on-creativity-my-modest-guide-to-being-more-creative/

**Comment by sahilc0** [comment]
https://medium.com/@thorbjoernkoenig/new-mnemonics-48f00b8bb68

**Comment by sahilc0** [comment]
https://twitter.com/FonsMans/status/1560662498290049025

**Comment by sahilc0** [comment]
https://twitter.com/FonsMans/status/1560244296082755584

**Comment by sahilc0** [comment]
https://github.com/BitcoinDesign/Meta/issues/322

**Comment by sahilc0** [comment]
https://uxdesign.cc/dark-mode-with-design-tokens-8d7b9d9753a

**Comment by sahilc0** [comment]
https://bitcoindesign.substack.com/p/bitcoin-design-update-31

**Comment by sahilc0** [comment]
https://twitter.com/max_guise/status/1557400948737069057

**Comment by sahilc0** [comment]
From the Cornman: https://mobile.twitter.com/RemitNotPaucity/status/1562319004563173376?s=20&t=sDMtbmH2A17RgfEeiLhtNA

**Comment by sahilc0** [comment]
https://twitter.com/bitcoinlake/status/1559936044946137091

**Comment by sahilc0** [comment]
Erika Hall quote (in mymind)

**Comment by sahilc0** [comment]
https://dergigi.com/2022/06/27/the-words-we-use-in-bitcoin/

**Comment by sahilc0** [comment]
benefits and challenges of island. Constraints, signing devices. https://twitter.com/nickmjones/status/1567589768631836687

**Comment by sahilc0** [comment]
https://bitcoindesign.substack.com/p/bitcoin-design-update-32

**Comment by sahilc0** [comment]
https://medium.com/salesforce-ux/what-you-need-to-know-about-the-new-salesforce-kinetics-system-ce10e9ae66a9

**Comment by sahilc0** [comment]
https://twitter.com/molly_hellmuth/status/1563178739009171462

**Comment by sahilc0** [comment]
carman suggested topci: qr codes (boring vs colored vs logo)

**Comment by sahilc0** [comment]
Dynamic island:
- Discussion around reachability, accessibility and if it matters or not https://twitter.com/wiseenberg/status/1568243174396641281
- https://twitter.com/Gavmn/status/1567594032284717056

**Comment by sahilc0** [comment]
https://twitter.com/bnj/status/1567604609715425281

**Comment by sahilc0** [comment]
https://twitter.com/ow/status/1569218096665341959

**Comment by sahilc0** [comment]
https://mobile.twitter.com/adhamdannaway/status/1569823781941657600?s=46&t=eEPFSxFvgwbz-4mon1gGLw

**Comment by sahilc0** [comment]
https://jarango.com/2022/09/15/against-superficial-simplicity/

**Comment by futurepaul** [comment]
https://event.bitcoin.design/
